#!/bin/sh
#Used to calculate checksum for Russound RNET commands

bcount=0
#For each hex byte, add "0x" so shell evaluates as hex
for field in $1; do
	field="0x$field"
	result=$((result+field))
	bcount=$(($bcount + 1)) 
done
checksum=$(((result+bcount) & 0x007F))
checksum=$(dec2hex $checksum)
echo "$checksum"
